version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989" # Map port 80 on the host to port 80 in the container
    container_name: my_product_web
    restart: unless-stopped
    # Ensure you have a .env file in your project root with
    # VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY
    env_file:
      - .env
    #
    # If you want to mount volumes (e.g., for development or persistent data):
    # volumes:
    #   - ./src:/app/src # Example: Mount src directory for live reloading (dev only)

# You can add other services here, like a database, backend API, etc.
# example_db:
#   image: postgres:15-alpine
#   ports:
#     - "5432:5432"
#   environment:
#     POSTGRES_USER: user
#     POSTGRES_PASSWORD: password
#     POSTGRES_DB: mydatabase
#   volumes:
#     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: # Defines a named volume for persistent database storage