// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftqbquzausvannumzsqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cWJxdXphdXN2YW5udW16c3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjUxOTUsImV4cCI6MjA2NDI0MTE5NX0.6dd_IKVpxFK2HnB6P8lLHnKEP_CSiQWp1Hc2q8eYqk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);